setup route for react & angular, created bear-bones ui with routing demo
rainclouded/Concierge pull request #130
Opened 2024-10-02 01:12 UTC by nateng98

2024-10-02 23:31 UTC, rainclouded requested changes

2024-10-02 23:31 UTC, rainclouded commented on src/guest_webapp/src/pages/AmenitiesPage.jsx
Please adjust the indentation

2024-10-02 23:31 UTC, rainclouded commented on src/guest_webapp/src/pages/HomePage.jsx
> +			<Link to='/'>Log out</Link>
Being pedantic, but here too please

2024-10-03 02:45 UTC, Mondane-Monkeys approved these changes
This is amazing, great work!

2024-10-03 17:02 UTC, nateng98 commented
There is an issue with Angular SSR right now (routing to nginx default on refresh instead of staying on Angular webapp)

2024-10-03 23:03 UTC, rainclouded commented
lgtm

2024-10-03 23:03 UTC, rainclouded approved these changes

2024-10-04 20:23 UTC, merged